language: java
jdk:
- oraclejdk8
os:
- linux
sudo: required
before_script:
- echo -e "Host $REMOTE_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
before_install:
- openssl aes-256-cbc -K $encrypted_dd63175e05d9_key -iv $encrypted_dd63175e05d9_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
- chmod +x deploy.sh
- sh deploy.sh
  addons:
    ssh_known_hosts:
      - $REMOTE_HOST
